[package]
name = "tropicam-py"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Python bindings for the TropiCam core"

[lib]
name = "tropicam_rs"
crate-type = ["cdylib"]

[dependencies]
tropicam-core = { path = "../tropicam-core" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py311"] }
